name: Terraform CI/CD

on: [push, pull_request]

env:
  TERRAFORM_VERSION: 1.10.5

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    environment: AWS-prod
    env:
      AWS_REGION: ${{ vars.TF_AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ vars.TF_AWS_ACCOUNT_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.TF_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - name: Terraform Init
        run: terraform init
      - name: Terraform Validate
        run: terraform validate
      - name: Terraform Plan
        run: terraform plan
      - name: Terraform Plan [Pull Request]
        if: github.event_name == 'pull_request'
        run: terraform plan -out .planfile
      - name: Post PR comment
        uses: borchero/terraform-plan-comment@v2
        if: github.event_name == 'pull_request'
        with:
          token: ${{ github.token }}
          planfile: .planfile
  # terraform-apply:
  #   runs-on: ubuntu-latest
  #   needs: terraform-plan
  #   environment: AWS-prod
  #   env:
  #     AWS_REGION: ${{ env.TF_AWS_REGION }}
  #     AWS_ACCOUNT_ID: ${{ env.TF_AWS_ACCOUNT_ID }}
  #     AWS_ACCESS_KEY_ID: ${{ secrets.TF_AWS_ACCESS_KEY_ID }}
  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Setup Terraform
  #       uses: hashicorp/setup-terraform@v3
  #       with:
  #         terraform_version: ${{ env.TERRAFORM_VERSION }}
  #     - name: Terraform Init
  #       run: terraform init
  #     - name: Terraform Apply
  #       if: github.ref == 'refs/heads/main' && github.event_name == 'push'
  #       run: terraform apply -auto-approve
